export const donationsTest = [
  {
    id: 1,
    title: "Donation 1",
    description: "This is donation request 1.",
    pending: true,
    completed: false,
    category: "Food",
    type: "Fruits",
  },
  {
    id: 2,
    title: "Donation 2",
    description: "This is donation request 2.",
    pending: false,
    completed: false,
    category: "Toys",
    age: "0-10",
    gender: "Male",
    subCategory: "Dolls",
  },
  {
    id: 3,
    title: "Donation 3",
    description: "This is donation request 3.",
    pending: false,
    completed: false,
    category: "Clothing",
    age: "0-10",
    gender: "Female",
    season: "Winter",
  },
  {
    id: 4,
    title: "Donation 4",
    description: "This is donation request 4.",
    pending: false,
    completed: false,
    category: "Clothing",
    age: "11-20",
    gender: "Male",
    season: "Summer",
  },
  {
    id: 5,
    title: "Donation 5",
    description: "This is donation request 5.",
    pending: false,
    completed: false,
    category: "Toys",
    age: "11-20",
    gender: "Female",
    subCategory: "Outdoor",
  },
  {
    id: 6,
    title: "Donation 6",
    description: "This is donation request 6.",
    pending: false,
    completed: false,
    category: "School Supplies",
    supplyType: "Stationary",
  },
  {
    id: 7,
    title: "Donation 7",
    description: "This is donation request 7.",
    pending: false,
    completed: false,
    category: "Medical Supplies",
    subCategory: "Medication",
  },
  {
    id: 8,
    title: "Donation 8",
    description: "This is donation request 8.",
    pending: false,
    completed: false,
    category: "Blood Donation",
    organization: "Governorate",
  },
  {
    id: 9,
    title: "Donation 9",
    description: "This is donation request 9.",
    pending: false,
    completed: false,
    category: "Food",
    type: "Vegetables",
  },
  {
    id: 10,
    title: "Donation 10",
    description: "This is donation request 10.",
    pending: false,
    completed: false,
    category: "Blood Donation",
    organization: "Hospital",
  },
  {
    id: 11,
    title: "Donation 11",
    description: "This is donation request 11.",
    pending: false,
    completed: false,
    category: "School Supplies",
    supplyType: "Books",
  },
];
